using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JG_Prospect.Common
{
    public enum HTMLTemplates
    {
        InterviewDateAutoEmail = 1,
        ActiveAutoEmail = 2,
        Additions = 3,
        Awnings = 4,
        Basements = 5,
        Bathrooms = 6,
        Contract_Template = 7,
        Custom = 8,
        Custom_Other = 9,
        Custom_Other_TM = 10,
        Custom_Template = 11,
        CustomerServiceAutoEmail =12,
        CustomerEmail_Template = 13,
        DeactiveAutoEmail  =14,
        Decking_ExteriorRailing = 15,
        Decking_Railing_Post_Columns = 16,
        Electric = 17,
        Equipment_And_Industry = 18,
        Excavating_And_StormWaterMNGMT = 19,
        Fascia_Capping_And_Soffit = 20,
        Fascia_Capping = 21,
        Fencing = 22,
        Flooring_Hardwood_Laminate_Vinyl = 23,
        Flooring_Marble_Porcelain_Ceramic = 24,
        Framing_Drywall_Insulation = 25,
        Framing_Drywall_Insulation_trim = 26,
        Gutters_And_GutterGuards = 27,
        Installer_Auto_Email = 28,
        Installer_Work_Order_template = 29,
        Kitchen_Test = 30,
        Kitchens = 31,
        Masonry_Flat_Work_And_RetainingWalls = 32,
        Masonry_Flat_Retaining_Walls = 33,
        Masonry_Siding = 34,
        New_Residential_Construction = 35,
        Offer_Made_Auto_Email = 36,
        OfferMade = 37,
        Painting = 38,
        Plumbing = 39,
        Post_Columns = 40,
        Prospecting_Auto_Email = 41,
        Repair_TM = 42,
        Roofing_Metal = 43,
        Roofing_Metal_Shake_Slate_Terracotta = 44,
        Roofing_Terracotta_Shake_Slate = 45,
        Roofing_Asphalt_And_Flat = 46,
        Roofing_Asphalt_Flat = 47,
        Sales_Auto_Email = 48,
        Service_Maintenance_And_Repair = 49,
        Shutters = 50,
        Siding_Masonry = 51,
        Siding_Vinyl = 52,
        Siding_Vinyl_Wood_Aluminum_Fiber_Cement = 53,
        Siding_Wood_Aluminum_Fiber_Cement = 54,
        Soffit = 55,
        Soffit_Template = 56,
        VendorCategoryEmail_Template = 57,
        VendorEmail_Template = 58,
        Windows_And_Doors = 59,
        Contract_AutoEmail_Template = 60,
        QuoteRequest = 61,
        Acceptance_And_Payment_Confirmation = 62,
        Proposal_Tracking_For_Not_Sold_Job = 63,
        Proposal_Tracking_For_Sold_Job = 64,
        Install_Category_Proposal_For_Not_Sold = 65,
        Install_Category_Proposal_For_Sold = 66,
        Estimate_Set_Appointment = 67,
        Ordered = 68,
        Active_Auto_Email = 69,
        Deactive_Auto_Email = 70,
        Task_Generator_Auto_Email = 71,
        Task_Assignment_Requested = 72
    }
}
